### ISSUE TITLE
Repository Format Gone Wrong 

### ISSUE THREAD

**Issue by frzana1012** [CSC207-UofT/course-project-csc207_stackoverflowers#38]
Camille made a pull request and then merged her push today but it ended up restructuring the repo, if anyone has the older (from yesterday) version of the repo, can you please push yours and change the repo? I'm not entirely sure how much of the repo has changed but I do know the text files are sort of messed up. The progress report also got deleted so I copied and pasted the progress report from history, if you wrote something in the progress report and it's not there anymore, that's why!!

**Comment by Maryyeah** [comment]
@frzana1012 ok I see the issue. I can't revert the pull request bc there are other things that were done after it. Next time when you approve, see which files they changed. Everything that is gone is in pull request #32 . See if you missed anything.

**Comment by Maryyeah** [comment]
I've reverted our main branch to the commit before everything went wrong. Since some people have commits that are after that, what you need to do is to merge main INTO your branch. If you are not sure you are doing it right, google. There might be conflicts when you merge. SOLVE THEM. DO NOT make everything match what you have now, especially if a file was deleted. @camillealve . Then, when you go onto the github website and create a new pull request, after selecting your branch and the main, you should be able to see if your modifications are still there. Check in file changes if the right ones are modified, and others are not. Then, yell on discord for others to check for you, so that we can merge pull requests as a group.
I was unable to revert the changes one by one, so that is why we are here. If you are to approve another person's pull request again, check ALL the files that are modified.
